language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run test:lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - OWNER_NAME=BrightspaceUILabs
  - REPO_NAME=accordion
  - SAUCE_USERNAME: Gaudi1
  # GITHUB_RELEASE_TOKEN
  - secure: iQJlyKlzyh6z82h1klupdOIUxqdCvp+osu/+VeU7lyiZGvD57YE5910EixlwGRHXPL7NWRXkyPufVj19cbuJmdEzMVd7VUY/O1E++L5d+CzTsiNnIA6c9G7rIbDFLqp49XLfGvkJsLzS0fbeGdBeKn5WPOPSOY/uBhMstqYX141Fv7zFyaHH/538sHfuVt0qYgpO9HODGv8Oho12oqjdbvYMKarzAiy9PtKjUnVrVLpiTo/ds3byrwFPqdY72x+m9F299w0RSbg4DvAMwFqaLPe1YTI15mK8uEPaLPUDajZvOYO3xST+4U4+cj5ZptEdxMDHo3q7zaaRm6x4ipMDtVCK5Tca3b7MeH2ryBZD0bMHZpDRmmtGt3Hmc/kW8WdRw86Q3oQ1mFrT1flax0O8lb0d8sjI/vdG8A6L4cpo4eYG2XPSx50h4dIckpyHemFc6llgjSlsLfo2WkPQkK/6NHHyYBMZSgwZso8A2HBjNPsFpVbfpqdaNF/qPmB+U9JfQ7nPaYgorJJzQTbNULO0eL4Bg5piRZMid8gkeN1uzE3bmjwlkUaw/Gd6VUlI7aX/Fe/W7qiXiNo12CL41FbipFkTTFWupkjUSY8Uvit3/P3B28Sc47CFoiRqq5dRjYLw5C9i0EPipoyP3ydNtWkLaYtxGHWP70+kTymNuyXIhw8=
  # SAUCE_ACCESS_KEY
  - secure: jxgx7dO0/aKA0hh7og6QpgKWLwuXFWgOJR1wq0Iy1S6X1I+mgsYXQn+MG5oqR45KwbqCiuA859HDRfUwH4jXSJnK53AumvNOjW2gPpABqFosdHQgIzA9e1QVf0aGz6soTDnZrMyYG9px0ho10dpoRlpPrY4Hf0ncIwIokI5pfhYCae93wj2Y3oXTu/c3gf9MFusJXIcVyvZzjE+6SsWPr91BZlAhKcEIDG2yPkK3AaII0tQ9OVEBiiLzWlqCCav7eoUGEmBYzImVst6IhGObv0xtK6PYjv/0bwTLZmitGGoKe9qWGq7QBoC5ajBgdrK6MQ7TdmW5OCMJwvUmq0rOdTp+aWXRZqXo2kDE3BioGPWPtM5zMNSW3ctGV8vwNA2Iapu9tz+yDr9jL3D8iefjVcjTLXhVCqW+gFbE1eD5owqXoERp5cycYosqB+Gf+6MnqOpkIKStqJ/Dgb9oTbk2E2LEP6GIh4lucX5AUa+JLf6KvDAkyqqkyCWxnLv+BSxTxVQ7ewNSlfZ+hNLVUK0mVOIhWvq4Tq+SOKzX5ESSR9P5bFjmwSAwJ+m0Ng3Rl1Dv+3NTqH5Q0drouPYbYVKZG248YKIvf2VdcM2lbPHUMlHLitV2epgt8uSgOttwXF62VXYLEvx03B8JYMZPEMlJHejKWT6uuZ80Pqsioz9cWmg=
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # f8ea......fb5e
    secure: kFjhWnAhVH7HJOOFg4goMchO4Di26azuFicMCDZ/qjJCw2VwIggg6QzZF1dAHuT71njslTlEp/Cxyps+3z1GenWfALMKMSFJUBTKSxcuD9tc/Y/+qRFyojBIlZ89CYiNlw+dRb07Dlhipl+yyfbKIPYUyrfy2ZcWObPLOj9J/FARNO4v2wslrGSg5NPfEzbGR3kr5R4KGD7tNU2knfKmELM92ESzrUnQS8YDmFN0pd3snT6gNXDxISMCqDTrlIQmW2dufxtp26In45yDfJnb3ymcZi46KQun1b8UU4UhCQ9hO20I63MRgjo4hhrZehgOIV3FCU/MsM7iv9M0YPCMMdQ8YG0N6kpzutRl0QyoH44+8Ct2/KjcqWpqSPCsPeiDscXennFh8rD55l9fx53w437pHlC8j3+i9cyLpdkVs02nWppmRZlYfzSaq1c5A5XtmppX60mGv5iSed5lrlGZfyFp6A3rYulvAUTp4LTLSxHbsOw129r1xSdoBOdzMB+QMznYEVZPcTKpZyJ05h7m8RYAWi82griGFVJf6PElmuv91HMwaqiPnjVSTiv0MjC49L+JLNtope7dUN9ROUR62sSoEGpH15/drNxkG0yRCpHBOHPYnw1gNuh80KmXonRTJGaSZFHB6mgl7P/32sC51oH2ILXW5rSbs/cQl3hrP94=
  on:
    tags: true
    repo: BrightspaceUILabs/accordion
